POST http://localhost:3003/studentdetails
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybG9nZ2VkIjp7ImNyZWRlbnRpYWxzIjp7InVzZXJOYW1lIjoidGF5eWFiIiwicGFzc3dvcmQiOiIkMmIkMTAkMTY2b0ZrZW1vLlVCOC5LS2xOaldtdUdZWEVBZmtJQ05uWUJyRnQydVBpYmM2dHVZUlNraS4iLCJyb2xlIjoic3R1ZGVudCJ9LCJzdHVkZW50SW5mbyI6eyJuYW1lIjpudWxsLCJkZXBhcnRtZW50IjpudWxsLCJzZWN0aW9uIjpudWxsLCJzZW1lc3RlciI6MX0sIl9pZCI6IjY0NmE0ZWRlZTlmYzc0MzZhYWE5MjgyYiIsImN1cnJlbnRDb3Vyc2VzIjpbXSwicHJldmlvdXNDb3Vyc2VzIjpbXSwiX192IjowfSwiaWF0IjoxNjg0Njk3NjYwfQ.Y_BMP58nXoDCSAR7cIwS4HiUEHo-wUx3LAWpNtTu1hA"
}

###

POST http://localhost:3003/getteachercourses